ssh $DFS_USERNAME@csel-kh1250-11.cselabs.umn.edu "pkill -u $DFS_USERNAME"
ssh $DFS_USERNAME@csel-kh1250-12.cselabs.umn.edu "pkill -u $DFS_USERNAME"
ssh $DFS_USERNAME@csel-kh1250-13.cselabs.umn.edu "pkill -u $DFS_USERNAME"
ssh $DFS_USERNAME@csel-kh1250-14.cselabs.umn.edu "pkill -u $DFS_USERNAME"
ssh $DFS_USERNAME@csel-kh1250-15.cselabs.umn.edu "pkill -u $DFS_USERNAME"
ssh $DFS_USERNAME@csel-kh1250-16.cselabs.umn.edu "pkill -u $DFS_USERNAME"
ssh $DFS_USERNAME@csel-kh1250-17.cselabs.umn.edu "pkill -u $DFS_USERNAME"
